<?php
namespace TYPO3\FLOW3\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120601164047 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE roebooks_shop_domain_model_book CHANGE description description LONGTEXT NOT NULL");
		$this->addSql("ALTER TABLE roebooks_shop_domain_model_review CHANGE comment comment LONGTEXT NOT NULL");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE roebooks_shop_domain_model_book CHANGE description description VARCHAR(255) NOT NULL");
		$this->addSql("ALTER TABLE roebooks_shop_domain_model_review CHANGE comment comment VARCHAR(255) NOT NULL");
	}
}

?>