<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130903123541 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE robertlemke_example_bookshop_domain_model_book DROP INDEX IDX_18A52A64C53D045F, ADD UNIQUE INDEX UNIQ_18A52A64C53D045F (image)");
		$this->addSql("ALTER TABLE robertlemke_example_bookshop_domain_model_book DROP FOREIGN KEY FK_18A52A64C53D045F");
		$this->addSql("ALTER TABLE robertlemke_example_bookshop_domain_model_book ADD CONSTRAINT FK_18A52A64C53D045F FOREIGN KEY (image) REFERENCES typo3_media_domain_model_image (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE robertlemke_example_bookshop_domain_model_book DROP INDEX UNIQ_18A52A64C53D045F, ADD INDEX IDX_18A52A64C53D045F (image)");
		$this->addSql("ALTER TABLE robertlemke_example_bookshop_domain_model_book DROP FOREIGN KEY FK_18A52A64C53D045F");
		$this->addSql("ALTER TABLE robertlemke_example_bookshop_domain_model_book ADD CONSTRAINT FK_18A52A64C53D045F FOREIGN KEY (image) REFERENCES typo3_flow_resource_resource (persistence_object_identifier)");
	}
}

?>