<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20170207113438 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription()
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('CREATE TABLE robertlemke_example_bookshop_domain_model_book (persistence_object_identifier VARCHAR(40) NOT NULL, category VARCHAR(40) DEFAULT NULL, image VARCHAR(40) DEFAULT NULL, title VARCHAR(255) NOT NULL, price INT NOT NULL, description LONGTEXT NOT NULL, isbn VARCHAR(255) NOT NULL, INDEX IDX_18A52A6464C19C1 (category), UNIQUE INDEX UNIQ_18A52A64C53D045F (image), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE robertlemke_example_bookshop_domain_model_category (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE robertlemke_example_bookshop_domain_model_review (persistence_object_identifier VARCHAR(40) NOT NULL, book VARCHAR(40) DEFAULT NULL, title VARCHAR(255) NOT NULL, author VARCHAR(255) NOT NULL, rating INT NOT NULL, comment LONGTEXT NOT NULL, INDEX IDX_2AEBC013CBE5A331 (book), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE robertlemke_example_bookshop_domain_model_user (persistence_object_identifier VARCHAR(40) NOT NULL, department VARCHAR(255) NOT NULL, company VARCHAR(255) NOT NULL, repositoryusername VARCHAR(255) NOT NULL, role VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, website VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE robertlemke_example_bookshop_domain_model_book ADD CONSTRAINT FK_18A52A6464C19C1 FOREIGN KEY (category) REFERENCES robertlemke_example_bookshop_domain_model_category (persistence_object_identifier)');
        $this->addSql('ALTER TABLE robertlemke_example_bookshop_domain_model_book ADD CONSTRAINT FK_18A52A64C53D045F FOREIGN KEY (image) REFERENCES neos_media_domain_model_image (persistence_object_identifier)');
        $this->addSql('ALTER TABLE robertlemke_example_bookshop_domain_model_review ADD CONSTRAINT FK_2AEBC013CBE5A331 FOREIGN KEY (book) REFERENCES robertlemke_example_bookshop_domain_model_book (persistence_object_identifier)');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('ALTER TABLE robertlemke_example_bookshop_domain_model_review DROP FOREIGN KEY FK_2AEBC013CBE5A331');
        $this->addSql('ALTER TABLE robertlemke_example_bookshop_domain_model_book DROP FOREIGN KEY FK_18A52A6464C19C1');
        $this->addSql('DROP TABLE robertlemke_example_bookshop_domain_model_book');
        $this->addSql('DROP TABLE robertlemke_example_bookshop_domain_model_category');
        $this->addSql('DROP TABLE robertlemke_example_bookshop_domain_model_review');
        $this->addSql('DROP TABLE robertlemke_example_bookshop_domain_model_user');
    }
}